version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
        # Ignore all grpcio and protobuf minor updates
      - dependency-name: "grpcio"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "protobuf"
        update-types: ["version-update:semver-minor"]
  - package-ecosystem: "pip"
    directory: "/poetry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        dependency-type: "development"
      production:
        dependency-type: "production"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
